# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_imdb', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=41)),
                ('poster', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[(3, 'admin'), (2, 'moderator'), (1, 'user'), (0, 'public_user')], max_length=11)),
                ('image', models.CharField(max_length=225)),
            ],
        ),
    ]
